name: LinBot
description: A bot made by jacklin213
version: 1.1.4

author: jacklin213
main: me.jacklin213.linbot.LinBot

commands:
  linbot:
    description: Main command

permissions:
  linbot.access:
    description: Gives initial access to LinBot
    default: op
  linbot.command.admin:
    children:
      linbot.command.date: true
      linbot.command.day: true
      linbot.command.fly: true
      linbot.command.god: true
      linbot.command.h: true
      linbot.command.heal: true
      linbot.command.initiate: true
      linbot.command.kill: true
      linbot.command.night: true
      linbot.command.rain: true
      linbot.command.random: true
      linbot.command.reload: true
      linbot.command.say: true
      linbot.command.shutdown: true
      linbot.command.status: true
      linbot.command.sun: true
      linbot.command.update: true
      linbot.command.whoami: true
    default: false
  linbot.command.mod:
    children:
      linbot.command.date: true
      linbot.command.day: true
      linbot.command.fly: true
      linbot.command.god: true
      linbot.command.h: true
      linbot.command.heal: true
      linbot.command.initiate: true
      linbot.command.kill: true
      linbot.command.night: true
      linbot.command.rain: true
      linbot.command.random: true
      linbot.command.say: true
      linbot.command.status: true
      linbot.command.sun: true
      linbot.command.whoami: true
    default: op